### ISSUE TITLE
xcode project archive failure

### ISSUE THREAD

**Issue by jiangweiqing** [gurhub/surmagic#14]
if let workspace = target.workspace {
            arguments.append("-workspace")
            arguments.append(workspace)
        } else if let project = target.project {
            arguments.append("-project \(project)")
            arguments.append(project)

only add once 'project'

**Comment by gurhub** [comment]
Hi @jiangweiqing, thank you for contributing! Please use the issue template when you're creating a new issue. You can [report a bug or suggest an idea for this project](https://github.com/gurhub/surmagic/issues/new/choose). 

Unfortunately currently not clear what do you asking.

**Comment by gurhub** [comment]
Thank you for your effort. Fixed on [version 1.2.7.](https://github.com/gurhub/surmagic/releases/tag/v1.2.7)
