### ISSUE TITLE
XCframework not generated

### ISSUE THREAD

**Issue by byaruhaf** [gurhub/surmagic#15]
## Describe the bug
XCframework not generated. 

## To Reproduce
1. clone [repo](https://github.com/byaruhaf/Wallet) 
2. Then run `surmagic xcf --verbose` 

## Expected behavior
I expect XCframework to be generated after the two archives have been created.

## Faulty behavior
I see the archives, created then an empty folder. 

## Extra Strange

when I run the command copied from the verbose[ log output](https://textbin.net/finfmsr4cx) from the surmagic failed command I do get the XCframework
i.e when I run the following 

```bash
xcodebuild archive -workspace WalletTest.xcworkspace -sdk iphonesimulator -scheme walletintel -archivePath ./build/iOSSimulator.xcarchive SKIP_INSTALL=NO

xcodebuild archive -workspace WalletTest.xcworkspace -sdk iphoneos -scheme walletarm -archivePath ./build/iOS.xcarchive SKIP_INSTALL=NO

xcodebuild -create-xcframework -framework ./build/iOS.xcarchive/Products/Library/Frameworks/walletarm.framework -framework ./build/iOSSimulator.xcarchive/Products/Library/Frameworks/walletintel.framework -output ./build/xcf.xcframework
```

## Youtube Video
https://youtu.be/cFympcNRWIw

## Details

```
 ❯ surmagic env                                                             [10:51:58]

 ℹ️  Printing the information:


 ---------------------------

1.2.5

 ---------------------------

Xcode 13.3.1
Build version 13E500a

 ---------------------------

ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258

 ---------------------------
```

## Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/gurhub/surmagic/issues)

**Comment by gurhub** [comment]
Hi @byaruhaf, thank you for sharing your error in an elegant way. 

I think you need to solve your code build warning first:

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS, id:00008030-001024212E91802E, name:Asterix, error:Asterix’s iOS 15.0 doesn’t match walletarm.framework’s iOS 15.4 deployment target. Upgrade Asterix’s iOS version or lower walletarm.framework’s deployment target. }
{ platform:iOS, id:00008030-001A1D941A40802E, name:Buba, error:Buba’s iOS 15.2 doesn’t match walletarm.framework’s iOS 15.4 deployment target. Upgrade Buba’s iOS version or lower walletarm.framework’s deployment target. }
{ platform:iOS, id:8c9fa8cacd7df82db9f08d3cce5af8c35166cf54, name:Getafix, error:Getafix’s iOS 14.2 doesn’t match walletarm.framework’s iOS 15.4 deployment target. Upgrade Getafix’s iOS version or lower walletarm.framework’s deployment target. }
{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:A6DE1FFD-24E8-58B1-8D40-38C3BC06DAEE }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }

```

You need to search for this issue on StackOverflow and solve it somehow. 

This issue is not related to the surmagic itself. That's why I'm closing the issue. 

Best

**Comment by gurhub** [comment]
Maybe one of the answers under this page might help to fix the issue: https://developer.apple.com/forums/thread/127212

**Comment by byaruhaf** [comment]
Thanks, @gurhub  will take a look.
