### ISSUE TITLE
Xcode 12 Build Targets

### ISSUE THREAD

**Issue by prin53** [gurhub/surmagic#5]
First of all, thank you for the script. 👍

I am using Xcode 12 and trying to build a universal framework. Before there was a single target for the Generic iOS Device, but now I have:

<img width="287" alt="Screenshot 2020-09-27 at 10 12 58" src="https://user-images.githubusercontent.com/4447833/94358508-43fc9880-00aa-11eb-8ec6-2d0d1b678e5f.png">

The framework will contain only one selected target (either i386/x86_64 or arm64/arm), so I can run it on either simulator or device. How can I build it with both architectures on Xcode 12?

**Comment by zhoulijun12315** [comment]
get the same problem

**Comment by gurhub** [comment]
Hi, this must be an issue with the new Xcode and need to be fixed, but for now, I don't have time to fix it. Anyway, I'll fix it as soon as possible this after busy days.

Meanwhile, don't hesitate to contribute ;) 
Solutions are welcome.

Best.

**Comment by gurhub** [comment]
Hi All, 

I just updated the project name and the project itself. Now you can create a universal framework with a command-line tool called surmagic. 

Please check the [latest-release](https://github.com/gurhub/surmagic/releases) to install an XCFramework without hassle. Of course, read the [README.md](https://github.com/gurhub/surmagic) first.

You can start to use the command below to create the default directory and Surfile:

`surmagic init`

Also, don't forget to remove the previous script (universal.sh) from your Scheme's Archive > Post-actions.

Best
