### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by Disconnecter** [gurhub/surmagic#7]
```
username$ surmagic init
mkdir: ./Surmagic: File exists

 📂 Created a directory: ./Surmagic

Fatal error: could not load resource bundle: from /usr/local/bin/surmagic_surmagic.bundle or /Users/mgy/Developer/surmagic/surmagic/.build/x86_64-apple-macosx/release/surmagic_surmagic.bundle: file surmagic/resource_bundle_accessor.swift, line 11
Illegal instruction: 4
```

**Comment by gurhub** [comment]
Hi @Disconnecter, 

Here are the possible causes:

* you don't need to recall the "surmagic init" if you already initialize the Surmagic directory 
* **if you have an executable file on the same directory with the same name**,  that's why you're facing the File exists error. 

Please [uninstall the Surmagic](https://github.com/gurhub/surmagic#uninstalling-surmagic) executable from your system and re-install (with brew tap again!) surmagic. Don't try to install it with other methods.

If you still having an issue while using it, let me know.

Best

Muhammed

**Comment by Disconnecter** [comment]
Hi @gurhub 
I installed via brew at first time

**Comment by gurhub** [comment]
So, did you solve the issue by re-installing the surmagic?

**Comment by gurhub** [comment]
Hi @Disconnecter,  I'm closing this one, if you have any issue with your configuration, please check the Demo project.

**Comment by Disconnecter** [comment]
> So, did you solve the issue by re-installing the surmagic?

No, I installed via brew as in faq and got this issue

**Comment by gurhub** [comment]
Hi @Disconnecter,

** Please complete the following information):**

- macOS version: [e.g. Big Sur 11.0.1 (20B29)]
- Bash name
- surmagic version (run: "surmagic --version")
- Share your 'Surfile' with us.

Best

**Comment by gurhub** [comment]
I'm asking does information because I guess it might be related to this: https://forums.swift.org/t/swift-5-3-spm-resources-in-tests-uses-wrong-bundle-path/37051.

Also, I have tried other machines that run on macOS Big Sur 11.0.1 (20B29). It's working like it's expected.

Best

**Comment by Disconnecter** [comment]
> Hi @Disconnecter,
> 
> ** Please complete the following information):**
> 
> * macOS version: [e.g. Big Sur 11.0.1 (20B29)]
> * Bash name
> * surmagic version (run: "surmagic --version")
> * Share your 'Surfile' with us.
> 
> Best

1. Catalina 10.15.6
2. bash
3. 1.2.0
4. 
`<dict>
  <key>output_path</key>
  <string>MY_OUTPUT_DIRECTORY_NAME_HERE_</string>
  <key>framework</key>
  <string>MY_FRAMEWORK_NAME_HERE_</string>
  <key>targets</key>
  <array>
    <dict>
      <key>sdk</key>
      <string>iOS</string>
      <key>workspace</key>
      <string>MY_WORKSPACE_NAME_HERE_.xcworkspace</string>
      <key>scheme</key>
      <string>MY_SCHEME_NAME_HERE_</string>
    </dict>
 <dict>
      <key>sdk</key>
      <string> iOSSimulator </string>
      <key>workspace</key>
      <string>MY_WORKSPACE_NAME_HERE_.xcworkspace</string>
      <key>scheme</key>
      <string>MY_SCHEME_NAME_HERE_</string>
    </dict>
  </array>
</dict>`

**Comment by gurhub** [comment]
Hi @Disconnecter, 

thank you for the information, but still, I couldn't find any old macOS version to test with it. I [released a newer version](https://github.com/gurhub/surmagic/releases). You can make a [clean/fresh install](https://github.com/gurhub/surmagic/wiki). 

Also, are you considering upgrading a [newer and faster version of macOS](https://support.apple.com/kb/sp833?locale=en_US) anytime soon? 

Best.

**Comment by gurhub** [comment]
I've tested it a couple of times in different machines now. When I run the following command:

surmagic init

and this is the result:

 📂 Created a directory: ./Surmagic


 🚚 Initialized default files in the directory.

I'm closing this one. 

📣 Announcement: for future cases, please use the newly created issue template of the project.

https://github.com/gurhub/surmagic/tree/master/.github/ISSUE_TEMPLATE
