### ISSUE TITLE
'createFramework(verbose:)' caused an unexpected error.

### ISSUE THREAD

**Issue by shubham14896** [gurhub/surmagic#9]
**Describe the bug**

**To Reproduce**
1. I run the command 'surmagic xcf'
2. See error 'createFramework(verbose:)' caused an unexpected error.'

**Expected behavior**

**Screenshots**

**macOS (please complete the following information):**
 - If you can, please share the output of the -surmagic env- command
 - Or, please share the list below:
  * macOS version, [e.g. Big Sur 11.1 (20C69)]
  * Swift version, [e.g. 5.3]

**Additional context**

**Comment by gurhub** [comment]
Hi @shubham14896, can you please check the Demo project and let me know the differences from yours. 

Best

**Comment by shubham14896** [comment]
<img width="656" alt="Screenshot 2021-05-10 at 8 23 43 PM" src="https://user-images.githubusercontent.com/24712232/117679192-ad5e9100-b1cd-11eb-9245-f2f631d0726f.png">
I downloaded the demo app, and tried running `surmagic xcf`

**Comment by shubham14896** [comment]
@gurhub Thanks for the revert i was using wrong sdk value in surfile

**Comment by gurhub** [comment]
Dear @shubham14896, I'm glad to hear that :)

Best

**Comment by AbhijitPatilSafexpay** [comment]
Hello I have updated all the value as per the surfile.
but my framework do not have a xcworkspace now what i can do to solve that ?

**Comment by gurhub** [comment]
Hello, You can use the "project" keyword instead of the "workspace". 

Hope it'll solve your case.
